apiVersion: v1
metadata:
  name: kube-lego
data:
  # modify this to specify your address
  lego.email: "knobby@burntsheep.com"
  # configre letencrypt's production api
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
  #lego.url: "https://acme-staging.api.letsencrypt.org/directory"
kind: ConfigMap
