apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sabnzbd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      nodeSelector:
        fileserv: "true"
      containers:
      - name: sabnzbd
        image: sabnzbd/sabnzbd
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SABNZBD_UID
          value: "1000"
        - name: SABNZBD_GID
          value: "1000"
        volumeMounts:
        - name: sabnzbd
          mountPath: /datadir
        - name: sabnzbd-downloads
          mountPath: /download
      volumes:
      - name: sabnzbd
        persistentVolumeClaim:
          claimName: sabnzbd
      - name: sabnzbd-downloads
        hostPath:
          path: /mnt/fileserv/Library
